name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Build static files
      run: |
        source venv/bin/activate
        python app.py
    - name: Debug Info
      run: |
        echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
        echo "PWD: $(pwd)"
        ls -la

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        publish_dir: ./build